help:
	python -B proj1.py -h

setup:
	pip install -r requirements.txt

run:
	python -B proj1.py --L 220 -v 1

task1:
	python -B tasks/task1.py

task2:
	python -B tasks/task2.py

task3:
	python -B tasks/task3.py

task4:
	python -B tasks/task4.py

task5:
	python -B tasks/task5.py
